### ISSUE TITLE
Marine region not fully recovered with gaz_geometry

### ISSUE THREAD

**Issue by lawleyjw** [lifewatch/mregions2#26]
I am trying to calculate the area for several marine regions and noticed that the area I was getting was smaller than expected. So I tried mapping the regions to look for inconsistencies. When I run the code below I get the image below it, but what it seems to be missing a large portion of the area that marine region should cover (see latest image). Am I missing any options with gaz_geometry or is there an issue here? I appreciate any assistance/advice.

```r
test <- gaz_geometry(26584, multipart=FALSE) #same things happens if multipart=TRUE
test_sf <- st_as_sf(test)
ggplot() +
  geom_sf(data = test_sf, fill = 'blue', color = 'black') +
  ggtitle("Pacific Part of Canada's EEZ") +
  theme_minimal()
```
![Screen Shot 2024-05-29 at 21 49 57](https://github.com/lifewatch/mregions2/assets/73448607/e0dc6ee7-3a66-4257-ba0d-b5587ad351d3)
<img width="712" alt="Screen Shot 2024-05-29 at 21 50 12" src="https://github.com/lifewatch/mregions2/assets/73448607/a8d7a209-f9c1-4c37-b34e-43be13b4d84d">

**Comment by bart-v** [comment]
Clearly the R code does not take into account the multiple polygons returned by the API @salvafern 
This works fine:
https://marineregions.org/rest/getGazetteerGeometries.jsonld/26584/

**Comment by salvafern** [comment]
The code was not considering a case when the geometry has one single source but two attributeValue(s) as here:

http://marineregions.org/mrgid/26584/geometries?source=80&attributeValue=25505
http://marineregions.org/mrgid/26584/geometries?source=80&attributeValue=25585

And only the first was being picked up. Should be fixed now.

``` r
library(mregions2)
library(ggplot2)
library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 8.2.1; sf_use_s2() is TRUE

test <- gaz_geometry(26584, multipart=FALSE) #same things happens if multipart=TRUE
test_sf <- st_as_sf(test)
ggplot() +
  geom_sf(data = test_sf, fill = 'blue', color = 'black') +
  ggtitle("Pacific Part of Canada's EEZ") +
  theme_minimal()
```

![](https://i.imgur.com/ZzZ1uWN.png)

<sup>Created on 2024-06-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

@lawleyjw Thanks a lot for spotting, please don't hesitate to raise more issues if you encountered any.

**Comment by lawleyjw** [comment]
Thanks @salvafern !

I am still getting the same issue though with other regions. See example below:
```r
> library(mregions2)
> library(ggplot2)
> library(sf)
Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE
> test <- gaz_geometry(8940, multipart=FALSE) #same things happens if multipart=TRUE
> test_sf <- st_as_sf(test)
> ggplot() +
+   geom_sf(data = test_sf, fill = 'blue', color = 'black') +
+   theme_minimal()
```
<img width="623" alt="Screen Shot 2024-06-24 at 14 10 32" src="https://github.com/ropensci/mregions2/assets/73448607/2f9e3adb-4a18-4782-ab0d-c16c6951f4cb">
<img width="816" alt="Screen Shot 2024-06-24 at 14 10 17" src="https://github.com/ropensci/mregions2/assets/73448607/d35406e4-b7c2-4dca-bc16-35611f05867a">

**Comment by salvafern** [comment]
I will have a look

**Comment by salvafern** [comment]
Hi @lawleyjw 

I cannot reproduce the issue

``` r
library(mregions2)
library(ggplot2)
library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 8.2.1; sf_use_s2() is TRUE

test <- gaz_geometry(8940, multipart=FALSE) #same things happens if multipart=TRUE
test_sf <- st_as_sf(test)
ggplot() +
  geom_sf(data = test_sf, fill = 'blue', color = 'black') +
  theme_minimal()
```

![](https://i.imgur.com/XcARIay.png)

<sup>Created on 2024-07-25 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Have you reinstalled the package after https://github.com/ropensci/mregions2/commit/5fc28d62a3129dfd847bb0a451b506035db06a31?

```r
devtools::install_github("ropensci/mregions2@HEAD")
```

**Comment by salvafern** [comment]
I assume the package had to be reinstalled. Feel free to reopen.
